version: '3.7'

services:
  postgres:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    networks:
      - postgres_network

networks:
  postgres_network:
    driver: bridge
